# Technologies that are not recognized by GitHub as programming languages
# The list should be alphabetized

angular:
    color: "#dd0031"
    name: Angular
    url: https://angular.io/
azure:
    color: "#33a6dd"
    name: Azure
    url: https://azure.microsoft.com/
django:
    color: "#0c4b33"
    name: Django
    url: https://www.djangoproject.com/
docker:
    color: "#35a0f0"
    name: Docker
    url: https://www.docker.com/
react:
    color: "#61dafb"
    name: React
    url: https://reactjs.org/
vuejs:
    color: "#3fb984"
    name: VueJs
    url: https://vuejs.org/
nodejs:
    color: "#80bd00"
    name: NodeJs
    url: https://nodejs.org
npm:
    color: "#c63737"
    name: Npm
    url: https://www.npmjs.com/